# Site
repository: https://github.com/MayankChaturvedi/MayankChaturvedi.github.io
favicon: images/favicon.ico

# Personal info
name: Mayank Chaturvedi
title: CSE22@BITSPilani | Software Developer | ICPC-20 Kanpur-Amritapuri Asia regionalist | TopCoder Open India-19
email: algorithmist.mayank@gmail.com

# Social links
github_username:  MayankChaturvedi
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: mayank-chaturvedi-a66335156
# pinterest_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Mayank and I have industry experience in software development, algorithmic optimisation and artificial intelligence. I am a seasoned competitive programmer, skilled in algorithms, C++, python. I am an information technology professional currently pursuing a Bachelors of Engineering- BE in Computer Science from Birla Institute of Technology and Science, Pilani.

  I am most skilled in: <mark>Server</mark> and <mark>Data Structures and Algorithms</mark>
  
  Have a look at my ICPC certifications : [Certificates](https://icpc.baylor.edu/ICPCID/9KUOMHVJNOLK). I have been placed 21st in Kanpur Asia ICPC'20 Regionals and 13th in TCO'19 India.

#Projects Section
#projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - I am president of programming club in my college
   - I am a mathematics major too. Having done research in the field of cryptography
   - I like trekking
   - I enjoy interacting and learning from people experienced in my field

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
